### ISSUE TITLE
Migration task

### ISSUE THREAD

**Issue by Augustyn** [Augustyn/JRMP#1]
There's need to implement migration task.
Task should be run on install, and perform check if there already is customfield 'Risk', and if it's appropriate type. If it's not, it should get every issue that uses invalid task and convert it to valid.

**Comment by Augustyn** [comment]
If there are risks with different custom field type, IndexOutOfBoundsException occurs, as fallows:

```
2015-06-27 09:03:35,766 ajp-bio-18009-exec-127 ERROR admin 543x35096x1 1ikn21d 10.105.228.38 /rest/jira-risk-management/1.0/controller/matrix [plugins.jrmp.rest.JRMPRisk
ManagementController] getMatrix: The Matrix couldn't be generated because of: Index: 5, Size: 5
java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
        at java.util.LinkedList.entry(LinkedList.java:365)
        at java.util.LinkedList.get(LinkedList.java:315)
        at net.amg.jira.plugins.jrmp.services.model.RiskIssuesModel.fillAllFields(RiskIssuesModel.java:115)
        at net.amg.jira.plugins.jrmp.services.model.RiskIssuesModel.<init>(RiskIssuesModel.java:53)
        at net.amg.jira.plugins.jrmp.services.MatrixGeneratorImpl.generateMatrix(MatrixGeneratorImpl.java:107)
```

Migration task should find all of those issues and migrate them to used custom field type.
